//! Network testing module - Tools to test network connectivity
//!
//! Not to be confused with tests/ (which tests our code)

pub mod ap_compat_matrix;
pub mod application;
pub mod auth_portal;
pub mod bufferbloat;
pub mod burst_analysis;
pub mod capacity_knee;
pub mod capture;
pub mod circuit_workflow;
pub mod clock_guard;
pub mod counter_liveness;
pub mod crypto_min;
pub mod dependency_health;
pub mod dhcp_lifecycle;
pub mod dns;
pub mod dns_secure;
pub mod dns_steering;
pub mod ecmp_nat;
pub mod ecn_aqm;
pub mod endpoint_registry;
pub mod firsthop;
pub mod fleet_orchestrator;
pub mod flow_dscp_matrix;
pub mod fuzzing;
pub mod gateway_bracket;
pub mod https;
pub mod iperf;
pub mod iperf_summary;
pub mod ipv6;
pub mod ipv6_validation;
pub mod listener_admission;
pub mod listener_lease;
pub mod media_quality;
pub mod mss_evidence;
pub mod mtu;
pub mod multicast_isolation;
pub mod nat_capacity;
pub mod packet_loss;
pub mod path_analysis;
pub mod pcap_report;
pub mod phy_normalized;
pub mod platform_matrix;
pub mod policy_manifest;
pub mod printer_raw;
pub mod probe_preflight;
pub mod probe_rate;
pub mod protocol_compare;
pub mod provider_path;
pub mod quic_pmtud;
pub mod reference_endpoint;
pub mod resilience;
pub mod rf_survey;
pub mod rtt;
pub mod run_confidence;
pub mod scenario;
pub mod second_network;
pub mod site_ab;
pub mod size_rate_matrix;
pub mod ssh_path;
pub mod stun;
pub mod tcp_health;
pub mod tcp_options_echo;
pub mod tcp_segmentation;
pub mod throughput_tuner;
pub mod tunnel_mss;
pub mod upload_sweep;
pub mod vpn_matrix;
pub mod wired_edge;

pub use dns_secure::DnsSecureCompareTest;
pub use https::{
    diagnose_mtu_blackhole, test_https_stages, CertInfo, HttpsDiagnosis, HttpsTestResult,
};
pub use printer_raw::Raw9100BulkTest;
pub use quic_pmtud::QuicPmtudTest;
pub use ssh_path::SshDataPathTest;
pub use tcp_options_echo::TcpOptionsEchoTest;
pub use upload_sweep::{UploadSizeSweepTest, DEFAULT_SIZES as UPLOAD_SWEEP_DEFAULT_SIZES};
